// This file is automatically generated. Do not edit it directly.
// NOTE: We pin to the live Lovable Cloud project below to defend against stale
// Vercel env vars that point at an old/wrong Supabase project. The anon key is
// public/safe to commit.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const PROJECT_REF = 'xfybnitxislnuetlltaz';
const FALLBACK_URL = `https://${PROJECT_REF}.supabase.co`;
const FALLBACK_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmeWJuaXR4aXNsbnVldGxsdGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNDk4ODAsImV4cCI6MjA4NzkyNTg4MH0.jU-68dDvy4jWHsWq3HES9idazywVcs-b6TyFc-cL9mw';

const envUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Only trust env values when they point at the correct project ref.
const SUPABASE_URL = envUrl && envUrl.includes(PROJECT_REF) ? envUrl : FALLBACK_URL;
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_URL === FALLBACK_URL ? FALLBACK_KEY : (envKey || FALLBACK_KEY);

if (envUrl && !envUrl.includes(PROJECT_REF)) {
  // Visible warning in production console so misconfigured deployments are obvious.
  // eslint-disable-next-line no-console
  console.warn(
    `[supabase] Ignoring VITE_SUPABASE_URL=${envUrl} — does not match expected project ${PROJECT_REF}. Using pinned ${FALLBACK_URL}.`,
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

export const SUPABASE_PROJECT_REF = PROJECT_REF;
export const SUPABASE_URL_RESOLVED = SUPABASE_URL;